import { describe, expect, it } from 'vitest';
import {
  IPTV_DEVICE_AK,
  aesGcmDecryptB64,
  aesGcmEncryptB64,
  buildVdnAppcommon,
  bytesToHex,
  compactJsonBytes,
  computeFingerprint,
  computeVdnCode,
  formEncode,
  formUrlencodeValue,
  generateAppRandomStr,
  javaStringHashcode,
  javaUuidFromHashes,
  md5Hex,
  nativeDay0Ms,
  rsaOaepSha256Encrypt,
  sha1Upper,
  sha256Hex,
  utf8,
} from './iptvDeviceCrypto';

// All expected values below were generated by executing the upstream
// ysp-live.py helpers directly (see /tmp/iptv-device-vectors.json), so the
// TypeScript port is pinned byte-for-byte against the reference implementation.
const fixedBytes = (length: number) => Uint8Array.from({ length }, (_, i) => i % 256);

describe('iptvDeviceCrypto hashes', () => {
  it('matches upstream sha1/sha256/md5 helpers', () => {
    expect(sha1Upper('hello')).toBe('AAF4C61DDCC5E8A2DABEDE0F3B482CD9AEA9434D');
    expect(sha256Hex('abc')).toBe('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
    expect(md5Hex('test')).toBe('098f6bcd4621d373cade4e832627b4f6');
  });

  it('matches upstream java hash/uuid helpers', () => {
    expect(javaStringHashcode('Hello')).toBe(69609650);
    expect(javaStringHashcode('ident')).toBe(100049392);
    expect(javaUuidFromHashes(69609650, -1234567890)).toBe('00000000042628b2ffffffffb669fd2e');
  });

  it('matches upstream native-day conversion and fingerprint', () => {
    expect(nativeDay0Ms(1700000000)).toBe(1699977600000);
    expect(computeFingerprint('xuid-test-001', 1700000000123)).toEqual([
      '9d32819036b91a79158f4e81aa326058b143524acb530687629664255d854c05',
      1700000000123,
      1699977600000,
    ]);
  });
});

describe('iptvDeviceCrypto AES-256-GCM', () => {
  it('encrypts and decrypts the upstream vector (raw bytes)', () => {
    const nonce = bytesToHex(fixedBytes(12));
    expect(nonce).toBe('000102030405060708090a0b');
    const b64 = aesGcmEncryptB64('secret-text', 'x'.repeat(32), fixedBytes);
    expect(b64).toBe('AAECAwQFBgcICQoLs1IVFSMSm2N9mwXgyrOK4/4M69ZSif/ExMlg');
    expect(aesGcmDecryptB64(b64, 'x'.repeat(32))).toBe('secret-text');
  });

  it('normalizes string keys like upstream', () => {
    const b64 = aesGcmEncryptB64('hello gcm world', 'test-key-0123456789abcdef012345', fixedBytes);
    expect(b64).toBe('AAECAwQFBgcICQoLnTFUOknj6G9iOiOGZShlnttCi33qPgXYdkW232bYJw==');
    expect(aesGcmDecryptB64(b64, 'test-key-0123456789abcdef012345')).toBe('hello gcm world');
  });

  it('rejects tampered ciphertext', () => {
    const b64 = aesGcmEncryptB64('hello gcm world', 'key', fixedBytes);
    const raw = atob(b64);
    const tampered = btoa(raw.slice(0, -1) + String.fromCharCode(raw.charCodeAt(raw.length - 1) ^ 1));
    expect(() => aesGcmDecryptB64(tampered, 'key')).toThrow('AES-GCM');
  });
});

describe('iptvDeviceCrypto RSA-OAEP-SHA256', () => {
  const DER_B64 =
    'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkKeLy4ywWLSnBkwRyqYgF3HMIj05V5uuh5HjyEsZOWnu1NHu3jPQv3sr32wwQNYv5qapsNXmNgLUDHtgHZxqPQAYXltjSRc0qhcD286t62wOIHId8zXS3s1Jy4rgU4qjQWzI9rp/1sE0pMsmwTaJa4zuJ5iz8VwF8Av5oJ1k+HxY+/HLnjNlW1hmWLpuDYmkZYuAoTHa1VGeHQh9FEKI8ZcL3GTQphShUoC+Kg3P1hGUVTtCYapmzPS5lkAdwebuzwvTCfGiTErYZCnPBUSeV7BVlgjtLYIi29KvF0a8FHsJMfe/UdHcyW/RihsIYOtDQcRRpFGXyPXbVrzFJse24QIDAQAB';

  it('reproduces the upstream ciphertext for a fixed seed', () => {
    const der = Uint8Array.from(atob(DER_B64), (c) => c.charCodeAt(0));
    const ct = rsaOaepSha256Encrypt(der, utf8('device-id-test-123'), fixedBytes(32));
    expect(bytesToHex(ct)).toBe(
      '08e19293ca8c32e206ab16a7ae201362f7c8448f625cbc54c13bd47e632b0a700a6bf91d2e9bb7399514c27d674b5aa21f5492140c3d651bcdae100c18861bed721be1b765da11e7f5670fc684c2f9a655cf03f42940626fdde0ca5410e8f0ffe83856c700160b415f3c67b4a29f43769effb0b41b301461f9392c9bd462b75787ab7b45ba99d436077550f290a1fd56c4f8e27130c848a310fcb3ebc5c8fc197d01684c3a1d011684146f00f45aa4c66e99a2a735e1fda98da4d535bcc4cb49e9de65a3f37d2a1691ea422101fff04ee2621ee9466ee4e5d8ad386527c8afc336037012cd5026d4182bad5c09d0c287fb4b6f170cead3ff70a3fa1bc95675f5',
    );
  });
});

describe('iptvDeviceCrypto wire encoders', () => {
  it('matches upstream form-urlencoding rules', () => {
    expect(formUrlencodeValue('a+b~c/d*e_f-g.h+i')).toBe('a%2Bb%7Ec%2Fd*e_f-g.h%2Bi');
    expect(new TextDecoder().decode(formEncode([['x', '1'], ['y', 'z w']]))).toBe('x=1&y=z+w');
  });

  it('matches upstream sorted compact json and slash escaping', () => {
    expect(new TextDecoder().decode(compactJsonBytes({ b: 1, a: { d: 2, c: [3] } }))).toBe('{"a":{"c":[3],"d":2},"b":1}');
    expect(new TextDecoder().decode(compactJsonBytes({ u: 'a/b' }, true))).toBe('{"u":"a\\/b"}');
  });

  it('matches upstream vdn helpers', () => {
    expect(buildVdnAppcommon('1.4.1')).toBe('{"adid":"","an":"央视频电视投屏助手","ap":"cctv_app_tv","av":"1.4.1"}');
    const [code, random] = computeVdnCode('secret', 'r4nd0m', fixedBytes);
    expect(code).toBe('26c796f23de63bb7f44ed92f0429c153');
    expect(random).toBe('r4nd0m');
  });

  it('generates upstream-shaped app random strings', () => {
    const value = generateAppRandomStr(fixedBytes);
    expect(value).toBe('00010203-0000-0001-0000-000000000001');
    expect(IPTV_DEVICE_AK).toBe('9f5c54c4ed0e50109b800f7e28fec205');
  });
});
