// Generated by scripts/sync-iptv-channels.mjs from https://garysclub.sharewithyou.dpdns.org/others/ysp-live.py
// Regenerate with: node scripts/sync-iptv-channels.mjs [--input <saved ysp-live.py>]

// Spoofed TV build fingerprints the device-protocol session registers
// under (upstream DEVICE_PROFILE_POOL).
export interface IptvDeviceProfileTemplate {
  source: string;
  brand: string;
  manufacturer: string;
  model: string;
  report_model: string;
  hardware: string;
  board: string;
  version_id: string;
  screen_param: string;
  cast_model: string;
}

export const IPTV_DEVICE_PROFILE_POOL: readonly IptvDeviceProfileTemplate[] = [
  {"source":"sony_8k_pool.XR-85Z9K","brand":"Sony","manufacturer":"Sony","model":"XR-85Z9K","report_model":"XR85Z9K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_85Z9K","screen_param":"7680-4320-280","cast_model":"XR-85Z9K"},
  {"source":"sony_8k_pool.XR-75Z9K","brand":"Sony","manufacturer":"Sony","model":"XR-75Z9K","report_model":"XR75Z9K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_75Z9K","screen_param":"7680-4320-260","cast_model":"XR-75Z9K"},
  {"source":"sony_8k_pool.XR-85Z9J","brand":"Sony","manufacturer":"Sony","model":"XR-85Z9J","report_model":"XR85Z9J","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2021.XR_85Z9J","screen_param":"7680-4320-280","cast_model":"XR-85Z9J"},
  {"source":"sony_8k_pool.XR-75Z9J","brand":"Sony","manufacturer":"Sony","model":"XR-75Z9J","report_model":"XR75Z9J","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2021.XR_75Z9J","screen_param":"7680-4320-260","cast_model":"XR-75Z9J"},
  {"source":"sony_8k_pool.KD-98ZG9","brand":"Sony","manufacturer":"Sony","model":"KD-98ZG9","report_model":"KD98ZG9","hardware":"mt5893","board":"mt5893","version_id":"SONYTV.2019.KD_98ZG9","screen_param":"7680-4320-320","cast_model":"KD-98ZG9"},
  {"source":"sony_8k_pool.KD-85ZG9","brand":"Sony","manufacturer":"Sony","model":"KD-85ZG9","report_model":"KD85ZG9","hardware":"mt5893","board":"mt5893","version_id":"SONYTV.2019.KD_85ZG9","screen_param":"7680-4320-280","cast_model":"KD-85ZG9"},
  {"source":"sony_8k_pool.KD-85ZH8","brand":"Sony","manufacturer":"Sony","model":"KD-85ZH8","report_model":"KD85ZH8","hardware":"mt5893","board":"mt5893","version_id":"SONYTV.2020.KD_85ZH8","screen_param":"7680-4320-280","cast_model":"KD-85ZH8"},
  {"source":"sony_8k_pool.KD-75ZH8","brand":"Sony","manufacturer":"Sony","model":"KD-75ZH8","report_model":"KD75ZH8","hardware":"mt5893","board":"mt5893","version_id":"SONYTV.2020.KD_75ZH8","screen_param":"7680-4320-260","cast_model":"KD-75ZH8"},
  {"source":"samsung_8k_pool.QA85QN900A","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN900A","report_model":"QA85QN900A","hardware":"s5e9925","board":"neo8k","version_id":"SAMSUNGTV.2021.QN900A","screen_param":"7680-4320-280","cast_model":"QA85QN900A"},
  {"source":"samsung_8k_pool.QA75QN900A","brand":"Samsung","manufacturer":"Samsung","model":"QA75QN900A","report_model":"QA75QN900A","hardware":"s5e9925","board":"neo8k","version_id":"SAMSUNGTV.2021.QN900A","screen_param":"7680-4320-260","cast_model":"QA75QN900A"},
  {"source":"samsung_8k_pool.QA85QN900B","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN900B","report_model":"QA85QN900B","hardware":"s5e9925","board":"neo8k","version_id":"SAMSUNGTV.2022.QN900B","screen_param":"7680-4320-280","cast_model":"QA85QN900B"},
  {"source":"samsung_8k_pool.QA75QN900B","brand":"Samsung","manufacturer":"Samsung","model":"QA75QN900B","report_model":"QA75QN900B","hardware":"s5e9925","board":"neo8k","version_id":"SAMSUNGTV.2022.QN900B","screen_param":"7680-4320-260","cast_model":"QA75QN900B"},
  {"source":"samsung_8k_pool.QA85QN900C","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN900C","report_model":"QA85QN900C","hardware":"s5e9935","board":"neo8k","version_id":"SAMSUNGTV.2023.QN900C","screen_param":"7680-4320-280","cast_model":"QA85QN900C"},
  {"source":"samsung_8k_pool.QA75QN900C","brand":"Samsung","manufacturer":"Samsung","model":"QA75QN900C","report_model":"QA75QN900C","hardware":"s5e9935","board":"neo8k","version_id":"SAMSUNGTV.2023.QN900C","screen_param":"7680-4320-260","cast_model":"QA75QN900C"},
  {"source":"samsung_8k_pool.QA85QN900D","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN900D","report_model":"QA85QN900D","hardware":"s5e9945","board":"neo8k","version_id":"SAMSUNGTV.2024.QN900D","screen_param":"7680-4320-280","cast_model":"QA85QN900D"},
  {"source":"samsung_8k_pool.QA98QN990C","brand":"Samsung","manufacturer":"Samsung","model":"QA98QN990C","report_model":"QA98QN990C","hardware":"s5e9935","board":"neo8k","version_id":"SAMSUNGTV.2023.QN990C","screen_param":"7680-4320-320","cast_model":"QA98QN990C"},
  {"source":"samsung_8k_pool.QA85QN800C","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN800C","report_model":"QA85QN800C","hardware":"s5e9935","board":"neo8k","version_id":"SAMSUNGTV.2023.QN800C","screen_param":"7680-4320-280","cast_model":"QA85QN800C"},
  {"source":"samsung_8k_pool.QA75QN800D","brand":"Samsung","manufacturer":"Samsung","model":"QA75QN800D","report_model":"QA75QN800D","hardware":"s5e9945","board":"neo8k","version_id":"SAMSUNGTV.2024.QN800D","screen_param":"7680-4320-260","cast_model":"QA75QN800D"},
  {"source":"lg_8k_pool.OLED88Z1PCA","brand":"LG","manufacturer":"LGE","model":"OLED88Z1PCA","report_model":"OLED88Z1PCA","hardware":"alpha9gen4","board":"lg8k","version_id":"LGTV.2021.OLED88Z1","screen_param":"7680-4320-320","cast_model":"OLED88Z1PCA"},
  {"source":"lg_8k_pool.OLED77Z1PCA","brand":"LG","manufacturer":"LGE","model":"OLED77Z1PCA","report_model":"OLED77Z1PCA","hardware":"alpha9gen4","board":"lg8k","version_id":"LGTV.2021.OLED77Z1","screen_param":"7680-4320-260","cast_model":"OLED77Z1PCA"},
  {"source":"lg_8k_pool.OLED88Z2PCA","brand":"LG","manufacturer":"LGE","model":"OLED88Z2PCA","report_model":"OLED88Z2PCA","hardware":"alpha9gen5","board":"lg8k","version_id":"LGTV.2022.OLED88Z2","screen_param":"7680-4320-320","cast_model":"OLED88Z2PCA"},
  {"source":"lg_8k_pool.OLED77Z2PCA","brand":"LG","manufacturer":"LGE","model":"OLED77Z2PCA","report_model":"OLED77Z2PCA","hardware":"alpha9gen5","board":"lg8k","version_id":"LGTV.2022.OLED77Z2","screen_param":"7680-4320-260","cast_model":"OLED77Z2PCA"},
  {"source":"lg_8k_pool.OLED88Z3PCA","brand":"LG","manufacturer":"LGE","model":"OLED88Z3PCA","report_model":"OLED88Z3PCA","hardware":"alpha9gen6","board":"lg8k","version_id":"LGTV.2023.OLED88Z3","screen_param":"7680-4320-320","cast_model":"OLED88Z3PCA"},
  {"source":"lg_8k_pool.OLED77Z3PCA","brand":"LG","manufacturer":"LGE","model":"OLED77Z3PCA","report_model":"OLED77Z3PCA","hardware":"alpha9gen6","board":"lg8k","version_id":"LGTV.2023.OLED77Z3","screen_param":"7680-4320-260","cast_model":"OLED77Z3PCA"},
  {"source":"lg_8k_pool.OLED88Z4PCA","brand":"LG","manufacturer":"LGE","model":"OLED88Z4PCA","report_model":"OLED88Z4PCA","hardware":"alpha9gen7","board":"lg8k","version_id":"LGTV.2024.OLED88Z4","screen_param":"7680-4320-320","cast_model":"OLED88Z4PCA"},
  {"source":"lg_8k_pool.86QNED99","brand":"LG","manufacturer":"LGE","model":"86QNED99","report_model":"86QNED99","hardware":"alpha9gen4","board":"lg8k","version_id":"LGTV.2021.86QNED99","screen_param":"7680-4320-300","cast_model":"86QNED99"},
  {"source":"sony_4k_pool.XR-85X95K","brand":"Sony","manufacturer":"Sony","model":"XR-85X95K","report_model":"XR85X95K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_85X95K","screen_param":"3840-2160-300","cast_model":"XR-85X95K"},
  {"source":"sony_4k_pool.XR-75X95K","brand":"Sony","manufacturer":"Sony","model":"XR-75X95K","report_model":"XR75X95K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_75X95K","screen_param":"3840-2160-280","cast_model":"XR-75X95K"},
  {"source":"sony_4k_pool.XR-65X90K","brand":"Sony","manufacturer":"Sony","model":"XR-65X90K","report_model":"XR65X90K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_65X90K","screen_param":"3840-2160-260","cast_model":"XR-65X90K"},
  {"source":"sony_4k_pool.XR-55X90K","brand":"Sony","manufacturer":"Sony","model":"XR-55X90K","report_model":"XR55X90K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_55X90K","screen_param":"3840-2160-240","cast_model":"XR-55X90K"},
  {"source":"sony_4k_pool.XR-65A95K","brand":"Sony","manufacturer":"Sony","model":"XR-65A95K","report_model":"XR65A95K","hardware":"mt5895","board":"mt5895","version_id":"SONYTV.2022.XR_65A95K","screen_param":"3840-2160-260","cast_model":"XR-65A95K"},
  {"source":"samsung_4k_pool.QA85QN90C","brand":"Samsung","manufacturer":"Samsung","model":"QA85QN90C","report_model":"QA85QN90C","hardware":"s5e9935","board":"neo4k","version_id":"SAMSUNGTV.2023.QN90C","screen_param":"3840-2160-300","cast_model":"QA85QN90C"},
  {"source":"samsung_4k_pool.QA75QN90C","brand":"Samsung","manufacturer":"Samsung","model":"QA75QN90C","report_model":"QA75QN90C","hardware":"s5e9935","board":"neo4k","version_id":"SAMSUNGTV.2023.QN90C","screen_param":"3840-2160-280","cast_model":"QA75QN90C"},
  {"source":"samsung_4k_pool.QA65QN90C","brand":"Samsung","manufacturer":"Samsung","model":"QA65QN90C","report_model":"QA65QN90C","hardware":"s5e9935","board":"neo4k","version_id":"SAMSUNGTV.2023.QN90C","screen_param":"3840-2160-260","cast_model":"QA65QN90C"},
  {"source":"samsung_4k_pool.QA55QN90C","brand":"Samsung","manufacturer":"Samsung","model":"QA55QN90C","report_model":"QA55QN90C","hardware":"s5e9935","board":"neo4k","version_id":"SAMSUNGTV.2023.QN90C","screen_param":"3840-2160-240","cast_model":"QA55QN90C"},
  {"source":"samsung_4k_pool.QA65S95C","brand":"Samsung","manufacturer":"Samsung","model":"QA65S95C","report_model":"QA65S95C","hardware":"s5e9935","board":"oled4k","version_id":"SAMSUNGTV.2023.S95C","screen_param":"3840-2160-260","cast_model":"QA65S95C"},
  {"source":"lg_4k_pool.OLED83C3PCA","brand":"LG","manufacturer":"LGE","model":"OLED83C3PCA","report_model":"OLED83C3PCA","hardware":"alpha9gen6","board":"lg4k","version_id":"LGTV.2023.OLED83C3","screen_param":"3840-2160-300","cast_model":"OLED83C3PCA"},
  {"source":"lg_4k_pool.OLED77C3PCA","brand":"LG","manufacturer":"LGE","model":"OLED77C3PCA","report_model":"OLED77C3PCA","hardware":"alpha9gen6","board":"lg4k","version_id":"LGTV.2023.OLED77C3","screen_param":"3840-2160-280","cast_model":"OLED77C3PCA"},
  {"source":"lg_4k_pool.OLED65C3PCA","brand":"LG","manufacturer":"LGE","model":"OLED65C3PCA","report_model":"OLED65C3PCA","hardware":"alpha9gen6","board":"lg4k","version_id":"LGTV.2023.OLED65C3","screen_param":"3840-2160-260","cast_model":"OLED65C3PCA"},
  {"source":"lg_4k_pool.OLED55C3PCA","brand":"LG","manufacturer":"LGE","model":"OLED55C3PCA","report_model":"OLED55C3PCA","hardware":"alpha9gen6","board":"lg4k","version_id":"LGTV.2023.OLED55C3","screen_param":"3840-2160-240","cast_model":"OLED55C3PCA"},
  {"source":"lg_4k_pool.86QNED90","brand":"LG","manufacturer":"LGE","model":"86QNED90","report_model":"86QNED90","hardware":"alpha7gen5","board":"lg4k","version_id":"LGTV.2022.86QNED90","screen_param":"3840-2160-300","cast_model":"86QNED90"},
  {"source":"tcl_8k_pool.85X925PRO","brand":"TCL","manufacturer":"TCL","model":"85X925 PRO","report_model":"85X925PRO","hardware":"mt9615","board":"tcl8k","version_id":"TCLTV.2021.X925PRO","screen_param":"7680-4320-280","cast_model":"85X925 PRO"},
  {"source":"tcl_8k_pool.75X925PRO","brand":"TCL","manufacturer":"TCL","model":"75X925 PRO","report_model":"75X925PRO","hardware":"mt9615","board":"tcl8k","version_id":"TCLTV.2021.X925PRO","screen_param":"7680-4320-260","cast_model":"75X925 PRO"},
  {"source":"tcl_4k_pool.85C845","brand":"TCL","manufacturer":"TCL","model":"85C845","report_model":"85C845","hardware":"mt9615","board":"tcl4k","version_id":"TCLTV.2023.C845","screen_param":"3840-2160-300","cast_model":"85C845"},
  {"source":"tcl_4k_pool.75C845","brand":"TCL","manufacturer":"TCL","model":"75C845","report_model":"75C845","hardware":"mt9615","board":"tcl4k","version_id":"TCLTV.2023.C845","screen_param":"3840-2160-280","cast_model":"75C845"},
  {"source":"tcl_4k_pool.65C845","brand":"TCL","manufacturer":"TCL","model":"65C845","report_model":"65C845","hardware":"mt9615","board":"tcl4k","version_id":"TCLTV.2023.C845","screen_param":"3840-2160-260","cast_model":"65C845"},
  {"source":"tcl_4k_pool.75C745","brand":"TCL","manufacturer":"TCL","model":"75C745","report_model":"75C745","hardware":"mt9615","board":"tcl4k","version_id":"TCLTV.2023.C745","screen_param":"3840-2160-280","cast_model":"75C745"},
  {"source":"tcl_4k_pool.65C745","brand":"TCL","manufacturer":"TCL","model":"65C745","report_model":"65C745","hardware":"mt9615","board":"tcl4k","version_id":"TCLTV.2023.C745","screen_param":"3840-2160-260","cast_model":"65C745"},
  {"source":"changhong_4k_pool.U65G7","brand":"CHANGHONG","manufacturer":"CHANGHONG","model":"U65G7","report_model":"U65G7","hardware":"mt9632","board":"changhong4k","version_id":"CHANGHONGTV.2022.U65G7","screen_param":"3840-2160-260","cast_model":"U65G7"},
  {"source":"changhong_4k_pool.U55G7","brand":"CHANGHONG","manufacturer":"CHANGHONG","model":"U55G7","report_model":"U55G7","hardware":"mt9632","board":"changhong4k","version_id":"CHANGHONGTV.2022.U55G7","screen_param":"3840-2160-240","cast_model":"U55G7"},
  {"source":"changhong_4k_pool.L55QCN1","brand":"CHANGHONG","manufacturer":"CHANGHONG","model":"L55QCN1","report_model":"L55QCN1","hardware":"mt9632","board":"changhong4k","version_id":"CHANGHONGTV.2021.L55QCN1","screen_param":"3840-2160-240","cast_model":"L55QCN1"},
  {"source":"changhong_4k_pool.U43QCN1","brand":"CHANGHONG","manufacturer":"CHANGHONG","model":"U43QCN1","report_model":"U43QCN1","hardware":"mt9632","board":"changhong4k","version_id":"CHANGHONGTV.2021.U43QCN1","screen_param":"3840-2160-220","cast_model":"U43QCN1"},
  {"source":"changhong_4k_pool.UD65YC5500UA","brand":"CHANGHONG","manufacturer":"CHANGHONG","model":"UD65YC5500UA","report_model":"UD65YC5500UA","hardware":"mt9632","board":"changhong4k","version_id":"CHANGHONGTV.2020.UD65YC5500UA","screen_param":"3840-2160-260","cast_model":"UD65YC5500UA"},
];
